# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-26 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_result', models.IntegerField(choices=[(0, '无'), (1, '有')], default=0, verbose_name='标注结果')),
                ('mark_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='标注时间')),
            ],
            options={
                'verbose_name': '标注结果',
                'verbose_name_plural': '标注结果',
            },
        ),
    ]
