# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-26 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_markresult_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='markresult',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marker', to=settings.AUTH_USER_MODEL, verbose_name='标注者'),
        ),
    ]
