# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-26 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_markresult_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='markresult',
            name='arbitrate_result',
            field=models.IntegerField(choices=[(0, '无'), (1, '有')], default=0, verbose_name='仲裁结果'),
        ),
        migrations.AddField(
            model_name='markresult',
            name='arbitrate_status',
            field=models.IntegerField(choices=[(0, '未判断'), (1, '无需仲裁'), (2, '需仲裁')], default=0, verbose_name='仲裁状态'),
        ),
    ]
