# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-26 14:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryDiseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwsExist', models.IntegerField(choices=[(1, '有'), (0, '无')], default=0, verbose_name='有无既往史')),
                ('DM_year', models.IntegerField(blank=True, default=0, verbose_name='糖尿病年数')),
                ('HTN_year', models.IntegerField(blank=True, default=0, verbose_name='高血压年数')),
                ('HPL_year', models.IntegerField(blank=True, default=0, verbose_name='高血脂年数')),
                ('pregnant_weeks', models.IntegerField(blank=True, default=0, verbose_name='妊娠周数')),
                ('left_diopter', models.IntegerField(choices=[(0, '正视'), (1, '低度近视'), (2, '中度近视'), (3, '高度近视'), (4, '远视')], default=0, verbose_name='左眼屈光度')),
                ('right_diopter', models.IntegerField(choices=[(0, '正视'), (1, '低度近视'), (2, '中度近视'), (3, '高度近视'), (4, '远视')], default=0, verbose_name='右眼屈光度')),
                ('family_diseases', models.TextField(blank=True, verbose_name='具体家族病')),
                ('father_eye_jws', models.CharField(blank=True, max_length=50, verbose_name='父亲既往史')),
                ('mother_eye_jws', models.CharField(blank=True, max_length=50, verbose_name='母亲既往史')),
                ('other_jws', models.CharField(blank=True, max_length=50, verbose_name='其他既往史')),
            ],
            options={
                'verbose_name': '既往病史',
                'verbose_name_plural': '既往病史',
            },
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('pk_patient_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='患者ID')),
                ('patient_name', models.CharField(max_length=20, verbose_name='患者姓名')),
                ('patient_gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=1, verbose_name='患者性别')),
                ('patient_age', models.IntegerField(default=0, verbose_name='患者年龄')),
                ('patient_tel', models.CharField(max_length=11, verbose_name='患者手机号')),
                ('patient_nation', models.CharField(blank=True, max_length=20, verbose_name='患者国籍')),
                ('ID_number', models.CharField(blank=True, max_length=18, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, max_length=30, verbose_name='患者住址')),
                ('parent_name', models.CharField(blank=True, max_length=20, verbose_name='家长姓名')),
                ('patient_birthday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='录入时间')),
                ('refine_weeks', models.IntegerField(default=0, verbose_name='矫正孕周')),
                ('refine_days', models.IntegerField(default=0, verbose_name='矫正孕天')),
                ('birth_weeks', models.IntegerField(default=0, verbose_name='出生孕周')),
                ('birth_days', models.IntegerField(default=0, verbose_name='出生孕天')),
                ('birth_weight', models.IntegerField(default=0, verbose_name='出生体重')),
                ('mother_ID_number', models.CharField(blank=True, max_length=18, verbose_name='母亲身份证号')),
                ('birth_way', models.IntegerField(choices=[(0, '剖腹产'), (1, '顺产'), (2, '产钳')], default=0, verbose_name='分娩方式')),
                ('whether_multi_birth', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否多胎')),
                ('pregnancy_syndrome', models.IntegerField(choices=[(0, '无'), (1, '糖尿病'), (2, '高血压'), (3, '甲减')], default=0, verbose_name='妊娠综合征')),
                ('father_eye_jws', models.CharField(blank=True, max_length=50, verbose_name='父亲眼病史')),
                ('mother_eye_jws', models.CharField(blank=True, max_length=50, verbose_name='母亲眼病史')),
                ('other_jws', models.CharField(blank=True, max_length=50, verbose_name='其他既往史')),
            ],
            options={
                'verbose_name': '患者信息表',
                'verbose_name_plural': '患者信息表',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=120, verbose_name='图片名称')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '患者眼底图片信息表',
                'verbose_name_plural': '患者眼底图片信息表',
            },
        ),
    ]
