# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-26 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalarea',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='report_module',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_hospital_area',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_mode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_ranks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_role',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='HospitalArea',
        ),
    ]
