# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-26 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220926_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.IntegerField(choices=[(0, '标注者'), (1, '仲裁者')], default=0, verbose_name='角色'),
        ),
    ]
