# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='task_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='任务名称'),
        ),
    ]
