# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-09-27 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tasktable_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='task_state',
            field=models.IntegerField(choices=[(0, '正常'), (1, '暂停')], default=0, verbose_name='任务状态'),
        ),
    ]
