# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-10-10 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221009_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskfinishstatus',
            name='marker',
        ),
        migrations.RemoveField(
            model_name='taskfinishstatus',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskFinishStatus',
        ),
    ]
