# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-10-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221010_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='arbitrate_status',
            field=models.IntegerField(choices=[(0, '未仲裁'), (1, '已仲裁')], default=0, verbose_name='任务仲裁状态'),
        ),
    ]
