# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-10-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_tasktable_arbitrate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='arbitrate_rules',
            field=models.IntegerField(blank=True, null=True, verbose_name='仲裁规则'),
        ),
    ]
